### ISSUE TITLE
Exception while creating a package which contains a LiveCopy 

### ISSUE THREAD

**Issue by smiakchilo** [exadel-inc/etoolbox-backpack#108]
When creating a package for a Page which must include LiveCopies, one may encounter an exception. The exception is due to the page has a corrupted live copy. That is, the path to the live copy contains a node without its `jcr:content` subnode, or else the live copy itself misses its `jcr:content`.
Package build may fail without any notification.
Expected result: 
1) Package build does not fail, and a valid package is created (however the "broken" live copies together with the subsequent live copies of the previous are skipped from the package)
2) An alert is displayed to the user with the error message. The error message says in which path the problem  occurred first. We have a single error message for every page that failed. If there are many messages, the alert popup must have scroll.

```
RangeIterator relationships = liveRelationshipManager.getLiveRelationships(resource, null, null);
```

**Comment by aliakseiTraihel** [comment]
Example of exaption: javax.jcr.ItemNotFoundException: No content resource for resource at path /content/hpe/base/blueprint/regression/components/global-header-nav-4-0/global-nav-4-0-no-jcr-content

**Comment by aliakseiTraihel** [comment]
<img width="966" alt="Screenshot 2023-11-09 at 10 59 31" src="https://github.com/exadel-inc/etoolbox-backpack/assets/94895287/dc399597-cdca-4b5b-9f09-d5848237ccaa">
