### ISSUE TITLE
Package build is slow

### ISSUE THREAD

**Issue by smiakchilo** [exadel-inc/etoolbox-backpack#109]
Sometimes when the package is being built using a JCR-SQL2 query, the building process is very slow (ca. 10 minutes for a 30Mb package containing just pages, no binary assets. There are not many references in the pages). The query itself runs in under a second.
Need to investigate what causes the slowness and fix it if possible.
Probably we need to put many timestamps and diagnose the bottlenecks.

**Comment by aliakseiTraihel** [comment]
new AssetReferenceSearch(node, DAM_ROOT, resourceResolver) takes some time, which when iterating over the paths list is summed up and felt
