### ISSUE TITLE
There is no ability to replicate the package without building it on the current envitonment

### ISSUE THREAD

**Issue by liubou-masiuk** [exadel-inc/etoolbox-backpack#118]
1. Create a package using backpack, download it
2. upload the package to another environment
3. try to replicate the package (with or without installing it first)

Actual result: the logs console shows a small message that the package should be built before replicating it
Expected result: The user can replicate the package without building it, the same way it is done in the Package manager

**Comment by aliakseiTraihel** [comment]
ERROR: Package by this path /etc/packages/EToolbox_BackPack/content-hpe-base-blueprint-regression-components-global-header-nav-4-0-global-nav-4-0-no-jcr-content-8.zip doesn't exist in the repository.
