### ISSUE TITLE
Remove unnecessary drop-down menu

### ISSUE THREAD

**Issue by AlKaliada** [exadel-inc/etoolbox-backpack#54]
![image_2021_10_05T11_34_29_494Z](https://user-images.githubusercontent.com/70597105/136014825-4ece5fe3-9f57-4cbc-9d51-31460c8e58c9.png)
Need to remove unnecessary drop-down menu 'Package' after pressing "Create" or "Upload" button in main menu

**Comment by nik132-eng** [comment]
hello, I want to work on this. can you please assign me this issue? I am new at the open-source contribution

**Comment by AlKaliada** [comment]
@nik132-eng hello, are going to open PR?

**Comment by DYevhen** [comment]
@AlKaliada assign me
