### ISSUE TITLE
Change style of the button

### ISSUE THREAD

**Issue by AlKaliada** [exadel-inc/etoolbox-backpack#55]
![image_2021_10_05T11_42_31_472Z](https://user-images.githubusercontent.com/70597105/136015901-f5d81e21-eeee-492a-99f9-9f7e80a52f1d.png)
Need to change style of the "CRX Package Manager" button in main menu for general style or more visible

**Comment by mayank-kr** [comment]
I would like to contribute, please assign me  this issue

**Comment by rigved-telang** [comment]
Hey, can I try? I am still a newbie to open source as well as web development but I would like to give it a try.

**Comment by AlKaliada** [comment]
You are welcome)

**Comment by DYevhen** [comment]
@AlKaliada assign me
