### ISSUE TITLE
Change default package group

### ISSUE THREAD

**Issue by AlKaliada** [exadel-inc/etoolbox-backpack#56]
![image_2021_10_05T12_19_43_923Z](https://user-images.githubusercontent.com/70597105/136020710-bc69c853-0542-4943-98ae-d8478a889145.png)
Need to change default package group from "EToolbox BackPack" to "All packages"

**Comment by TomasKonkol** [comment]
Hey @pospielov  can I work on this issue?

**Comment by DYevhen** [comment]
@AlKaliada assign me
