### ISSUE TITLE
Change message for no assets in test build

### ISSUE THREAD

**Issue by AlKaliada** [exadel-inc/etoolbox-backpack#57]
![image_2021_10_05T12_25_51_967Z](https://user-images.githubusercontent.com/70597105/136022187-3371d54a-789d-4c7e-82f3-afad84f67955.png)
Need to change message from 'Approximate size of the assets in the package: 0 Bytes' to 'There are no assets in the package' in  package page

**Comment by Simba-97** [comment]
Hello @AlKaliada can I work on this issue. Can you please assign it to me.?
