### ISSUE TITLE
Add backpack icon to Sites panel

### ISSUE THREAD

**Issue by AliakseiKaliada** [exadel-inc/etoolbox-backpack#66]
![image](https://user-images.githubusercontent.com/93247401/139909644-48eacb62-fc92-431d-9845-dc1d8a7bdcba.png)
Should add backpack icon to Sites panel (see picture), by clicking backpack icon open "create package" dialog, with filled paths by selected content

**Comment by DYevhen** [comment]
@AlKaliada assign me
